### ISSUE TITLE
把所有下载都暂停之后    过几分钟 会都失败

### ISSUE THREAD

**Issue by huicuihui** [guowilling/SRDownloadManager#13]
把所有的下载都暂停了,  等待一段时间,   会走代理方法- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error
报错: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x610000054cd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://yxfile.idealsee.com/9f6f64aca98f90b91d260555d3b41b97_mp4.mp4, NSErrorFailingURLKey=http://yxfile.idealsee.com/9f6f64aca98f90b91d260555d3b41b97_mp4.mp4, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

**Comment by guowilling** [comment]
呃, 暂停后过段时间, 系统可能会自动判定为超时, 我先看看是否有解决方案.
