### ISSUE TITLE
友情提示：两个问题和解决方案

### ISSUE THREAD

**Issue by huang-kun** [guowilling/SRDownloadManager#21]
@guowilling  我在公司项目中使用了SRDownloadManager，感觉还是不错的，目前发现两个问题：

问题1. 下载过程中的plist写入操作崩溃：

在批量下载多个文件时，在这里会出现崩溃，原因是`Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSCFDictionary: 0x2815d2680> was mutated while being enumerated.'`

```
- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveResponse:(NSURLResponse *)response completionHandler:(nonnull void (^)(NSURLSessionResponseDisposition))completionHandler {
    ...
    // 崩溃在这里
    [self.filesTotalLengthPlist writeToFile:SRFilesTotalLengthPlistPath atomically:YES];
    ...
}
```

分析原因：

下载开始时会从主线程里对这个字典进行读写操作，下载回调代理`didReceiveResponse`也会对字典进行读写操作，但是发生其他线程中；而批量下载很容易导致同时在多个线程中对该字典进行读写，造成冲突。

解决方案：

1. 建议对可能在多线程中使用的集合属性使用atomic关键字
2. 只用atomic还不够，因为该关键字只是用来保护set和get方法，不包含其他读写操作，所以我选择在[filesTotalLengthPlist writeToFile:]方法前后再进行锁操作，由于源码中两次分别在不同线程中使用了writeToFile，考虑到NSLock对线程也会敏感，因此使用了两个NSLock对象来做保护。

```
- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask didReceiveResponse:(NSURLResponse *)response completionHandler:(nonnull void (^)(NSURLSessionResponseDisposition))completionHandler {
    ...
    [self.lock1 lock];
    self.filesTotalLengthPlist[SRFileName(downloadModel.URL)] = @(totalLength);
    [self.filesTotalLengthPlist writeToFile:SRFilesTotalLengthPlistPath atomically:YES];
    [self.lock1 unlock];
    ...
}

- (void)deleteDownloadedFileOfURL:(NSURL *)URL {
    ...    
    [self.lock2 lock];
    [self.filesTotalLengthPlist removeObjectForKey:SRFileName(URL)];
    [self.filesTotalLengthPlist writeToFile:SRFilesTotalLengthPlistPath atomically:YES];
    [self.lock2 unlock];
    ...
}
```

问题2. 我们项目中使用了自己定义的下载目录，由于其他清理文件的操作导致了下载目录被删除，但是SRDownloadManager并不知情，所以下次下载文件时，总是出现`file download incomplete`的问题。

分析原因：

由于下载目录的缺失，执行到`[outputStream open]`会因为找不到目录而导致出错，这时候`outputStream.streamError`会出现`Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={_kCFStreamErrorCodeKey=2, _kCFStreamErrorDomainKey=1}`的问题

解决方案：

1. 执行`[outputStream open]`后，建议检查下`outputSteam`的`streamError`或者`streamStatus`，可能这时候会有错误，需要重视
2. 执行`[outputStream write:maxLength:]`时建议拿到方法return的数据，如果返回`0`或者`-1`的话，说明写入出错，需要重视
3. 每次下载前，还是要确保下载目录一定得存在，如果没有还是要`[fileManager createDirectoryAtPath:]`

最后我解释一下为什么自己说了这么多，确没有帮你改掉并且提交`PR`呢？

1. 我的分析也不一定是标准答案，如果有问题，欢迎回复交流
2. 我的解决方案只是为了给自己的项目打补丁，我相信你的解决方案也许会比我的更好
3. 推荐使用单元测试来进一步提升代码质量

正好今天是`程序员节`, So thanks for open source. Wish for the best!

**Comment by guowilling** [comment]
第一个问题确实是多线程读写造成的, 后来在项目中也遇到了, 然后也是加了层锁修复的. 第二个问题我还没有遇到过, 但肯定也是存在的, 当时只是觉得不增加复杂度, 如果需要清除缓存, 就调用提供的相应方法, 没有考虑到外界直接删除了缓存文件夹等情况, 你的解决方案都很好, 谢谢你的意见.
因为之前工作和生活不是很顺, 后来换了工作公司项目上又很忙, GitHub 上自己的仓库就没有很用心的去维护, 这里说句很抱歉.

**Comment by huang-kun** [comment]
看到你开源下载思路其实就很赞了，我也是因为你的库才接触到NSOutputStream，相互学习～
