### ISSUE TITLE
希望可以支持cocoapods集成

### ISSUE THREAD

**Issue by ZuYuanZhou** [guowilling/SRDownloadManager#4]
希望可以支持cocoapods集成

**Comment by guowilling** [comment]
主要我在考虑再写一个基于 downloadTast 的下载管理类, 想写好后再提供 CocoaPods 集成.
但最近准备换工作, 所以暂时搁置了, 之后会支持 CocoaPods 的.

**Comment by ZuYuanZhou** [comment]
是的. 我也是想如果用 URLSessionDownloadTask 是会更好.

**Comment by guowilling** [comment]
暂时已经支持 CocoaPods.
URLSessionDownloadTask 只有以后有时间了再添加了.
