### ISSUE TITLE
好像有内存泄漏

### ISSUE THREAD

**Issue by ruanqiaohua** [guowilling/SRDownloadManager#6]
我用Xcode自带的内存工具检测，检测到下载的时候存在leaks。

**Comment by guowilling** [comment]
好的, 谢谢你的反馈.
最近我有点忙, 可能暂时不会去处理你提的问题, 等忙完我会尽快排查你提的 Issues.
或者你有时间的话, 可以提供下解决方案直接 Pull request, 我会非常感谢.

**Comment by ruanqiaohua** [comment]
新版本检测没发现有内存泄漏，可以关闭了。
